# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Li Gen
title: Second-year master student
email: ligen@skku.edu
website: https://reagan1311.github.io/

# Social links
#twitter_username: facespics
github_username:  Reagan1311
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Li Gen and I'm a Second-year master student at Sungkyunkwan University, majoring in Electrical
  and Computer Engineering.

  Education:
  - Sungkyunkwan University, 2018-2020(expected), Suwon, South Korea
  - Xidian University, 2014-2018, Xi'an China

  Research Interests: <mark>Semantic Segmentation</mark> <mark>Object Detection</mark>
  <mark>Instance Segmentation</mark> <mark>Computer Vision</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Publication

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Computer Vision some of my other interests and hobbies are:
   - Badminton
   - Music
   - Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
