# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Li Gen
title: Second-year master student
email: ligen@skku.edu
website: https://reagan1311.github.io/

# Social links
#twitter_username: facespics
github_username:  Reagan1311
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Biography <a href="https://reagan1311.github.io/cv.pdf">{CV}</a>
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a second-year master student at Sungkyunkwan University, majoring in Electrical
  and Computer Engineering.
  Before that, I received the bachelor's degree in Electronic and Information Engineering from Xidian University, Xi’an, China, in 2018.

  Research interests:
  - Computer Vision and Deep learning
  - Semantic Segmentation, Object Detection and Intance Segmentation

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Publication

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Computer Vision some of my other interests and hobbies are:
   - Badminton
   - Music
   - Fitness

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
